### ISSUE TITLE
Cannot find module '@mycomp/ui-sdk/i18n' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Viktor-Bredihin** [rothsandro/angular-library-example#5]
in button.component.ts you have an import
`import { TranslatePipe } from '@mycomp/ui-sdk/i18n';`

which works only until you use it like this or any other way
`constructor(private pipe: TranslatePipe) {
    console.log(pipe);
  }` 

As soon as you use TranslatePipe anyhow it stops working in the consumer app with the next error
` [ERROR] TS2307: Cannot find module '@mycomp/ui-sdk/i18n' or its corresponding type declarations. [plugin angular-compiler]

    ../../angular-library-example/dist/mycomp/ui-sdk/button/src/button.component.d.ts:1:30:
      1 │ import { TranslatePipe } from '@mycomp/ui-sdk/i18n';
`

**Comment by Viktor-Bredihin** [comment]
@rothsandro 
https://github.com/Viktor-Bredihin/angular-library-example, the error appears when you use it in consumer app
![Uploading Screenshot from 2024-03-29 11-37-26.png…]()

**Comment by rothsandro** [comment]
The screenshot is broken. You need to add the pipe as provider if you want to inject it. But apart from that, your reproduction works fine for me and I don't see any TypeScript error.

**Comment by Viktor-Bredihin** [comment]
![Screenshot from 2024-03-29 11-37-26](https://github.com/rothsandro/angular-library-example/assets/2298048/2eb64d51-c9f7-4135-a21e-e622b380cdf7)

**Comment by Viktor-Bredihin** [comment]
@rothsandro 
how did you check? As I said you won't see any compiler errors in the app, the error appears only when you install it and use in another angular application (consumer app)

**Comment by Viktor-Bredihin** [comment]
it works in showcase because of the paths in tsconfig.json, but you can't do the same in a separated app

**Comment by Viktor-Bredihin** [comment]
@rothsandro 
I have fixed the problem by changing paths of my consumer app to
`"@mycomp/ui-sdk/*": ["node_modules/@mycomp/ui-sdk/*"],
      "@mycomp/ui-sdk": ["node_modules/@mycomp/ui-sdk"]`

I guess it was pretty obvious, sorry I bothered you with it. But I have never seen any other libraries required to add paths in tsconfig.json like this, do you think it's a good practice? I was thinking to just use separated npm package to avoid it

**Comment by rothsandro** [comment]
It should not be needed to configure paths in the consumer app.

I just tested it with a separate app. Just logging the ButtonComponent without actually using the button works fine. Actually using the component in the app results in a runtime error but not the TypeScript error you mentioned. The error only occurs when using npm link and can be fixed by configuring `preserveSymlinks` in the angular config.

If your setup is correct (everything built correctly, npm link correctly setup, no angular cache issue) and `preserveSymlinks` also doesn't help, I would need a reproduction that includes separate minimal app and the exact steps you do. Or you can just keep the paths workaround if you're happy with that.

**Comment by Viktor-Bredihin** [comment]
here is my consumer app https://github.com/Viktor-Bredihin/angular-widgets. For now I'm thinking to create a separated npm package, but if you can make it work without paths in consumer app it would be great, thank you very much for your time

**Comment by jkoervers** [comment]
I also get this error. I published the library with verdaccio and installed it in an app. Did you ever manage to install this library in an app?
